<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PriceCalculation extends Model
{
    use HasFactory;

    protected $fillable = [
        'product_name',
        'box_type_selection',
        'quantity',
        'custom_profit_input',
        'include_knife_cost',
        'atas_panjang',
        'atas_lebar',
        'atas_tinggi',
        'bawah_panjang',
        'bawah_lebar',
        'bawah_tinggi',
        'is_board_included',
        'is_cover_luar_included',
        'is_cover_dalam_included',
        'is_busa_included',
        'selected_items_ids',
        'raw_board_panjang_kertas',
        'raw_board_lebar_kertas',
        'raw_cl_panjang_kertas',
        'raw_cl_lebar_kertas',
        'raw_cd_panjang_kertas',
        'raw_cd_lebar_kertas',
        'raw_busa_panjang_material',
        'raw_busa_lebar_material',
        'dim_board_atas_p', 'dim_board_atas_l',
        'dim_board_bawah_p', 'dim_board_bawah_l',
        'dim_board_kuping_p', 'dim_board_kuping_l',
        'dim_board_lidah_p', 'dim_board_lidah_l',
        'dim_board_selongsong_p', 'dim_board_selongsong_l',
        'dim_cl_atas_p', 'dim_cl_atas_l',
        'dim_cl_bawah_p', 'dim_cl_bawah_l',
        'dim_cl_kuping_p', 'dim_cl_kuping_l',
        'dim_cl_lidah_p', 'dim_cl_lidah_l',
        'dim_cl_selongsong_p', 'dim_cl_selongsong_l',
        'dim_cd_atas_p', 'dim_cd_atas_l',
        'dim_cd_bawah_p', 'dim_cd_bawah_l',
        'dim_cd_lidah_p', 'dim_cd_lidah_l',
        'dim_cd_selongsong_p', 'dim_cd_selongsong_l',
        'dim_busa_p', 'dim_busa_l',
        'final_qty_board_atas',
        'final_qty_board_bawah',
        'final_qty_board_kuping',
        'final_qty_board_lidah',
        'final_qty_board_selongsong',
        'final_qty_cl_atas',
        'final_qty_cl_bawah',
        'final_qty_cl_kuping',
        'final_qty_cl_lidah',
        'final_qty_cl_selongsong',
        'final_qty_cd_atas',
        'final_qty_cd_bawah',
        'final_qty_cd_lidah',
        'final_qty_cd_selongsong',
        'final_qty_busa',
        'unit_price_board_atas',
        'unit_price_board_bawah',
        'unit_price_board_kuping',
        'unit_price_board_lidah',
        'unit_price_board_selongsong',
        'unit_price_cl_atas',
        'unit_price_cl_bawah',
        'unit_price_cl_kuping',
        'unit_price_cl_lidah',
        'unit_price_cl_selongsong',
        'unit_price_cd_atas',
        'unit_price_cd_bawah',
        'unit_price_cd_lidah',
        'unit_price_cd_selongsong',
        'unit_price_busa',
        'master_cost_size_selected',
        'master_cost_production_rate',
        'master_cost_knife_rate',
        'master_cost_profit_percentage',
        'poly_dimension_selected',
        'poly_cost_rate',
        'summary_total_material_cost',
        'summary_total_production_work_cost',
        'summary_total_poly_cost',
        'summary_actual_knife_cost',
        'summary_profit_percentage_applied',
        'summary_total_profit_amount',
        'summary_selling_price_per_item',
        'total_price_estimate_numeric',
        'total_price_estimate_display',
        'notes',
    ];

    protected $casts = [
        'selected_items_ids' => 'array',
        'is_board_included' => 'boolean',
        'is_cover_luar_included' => 'boolean',
        'is_cover_dalam_included' => 'boolean',
        'is_busa_included' => 'boolean',
        // Tambahkan casting untuk float/decimal jika perlu presisi spesifik
        // 'atas_panjang' => 'float',
        // 'unit_price_board_atas' => 'decimal:4',
    ];
}